name: reposteria-rosita

services:
  frontend:
    build: .
    container_name: pasteleria_frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
