server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Todas las rutas que no sean archivos se dirigen al index.html de React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para recursos estáticos generados por Vite
    location ~* \.(?:css|js|jpg|svg|png|jpeg|gif|ico|woff2?|eot|ttf|otf)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}
